"""
Bake per-part macaron colors into the partnext condition / assembly GLBs.

Each source GLB is a trimesh.Scene with N geometries (``geometry_0`` ... ``geometry_{N-1}``).
Within an example, the i-th geometry in ``view_input.glb`` corresponds to the i-th geometry
in ``view_assembly_9.glb`` (verified: matching vertex counts at each index). Assigning the
same palette by index therefore keeps the part-to-color mapping consistent across the
Condition and Assembly viewers on the project page.

Outputs are written next to the originals as ``view_input_colored.glb`` and
``view_assembly_9_colored.glb`` so the originals stay untouched.

Usage:
    python3 scripts/recolor_partnext.py
"""

from __future__ import annotations

from pathlib import Path

import numpy as np
import trimesh
from trimesh.visual.material import PBRMaterial
from trimesh.visual import TextureVisuals


# Per-part outward displacement applied ONLY to condition (view_input) files,
# so the "unposed parts" viewer doesn't pile everything at the origin. Each
# part's vertices are translated by EXPLODE_FACTOR * (part_center - pivot),
# where pivot is the mean of all part centers in that scene. 0.0 = no change,
# 1.0 = double the original distance from the pivot.
EXPLODE_FACTOR = 1.0


# Pastel "macaron" palette as RGBA floats in [0, 1]. Kept in sync with the
# fallback palette in static/js – not used at runtime anymore, but useful for
# anyone tweaking colors later.
MACARON = [
    (0.965, 0.620, 0.680, 1.0),  # rose
    (0.580, 0.855, 0.745, 1.0),  # sage mint
    (0.700, 0.730, 0.910, 1.0),  # periwinkle
    (0.985, 0.770, 0.640, 1.0),  # salmon peach
    (0.975, 0.855, 0.530, 1.0),  # honey
    (0.600, 0.815, 0.965, 1.0),  # cornflower
    (0.830, 0.650, 0.860, 1.0),  # orchid
    (0.970, 0.510, 0.590, 1.0),  # strawberry coral
    (0.670, 0.870, 0.620, 1.0),  # pistachio
    (0.970, 0.660, 0.860, 1.0),  # bubblegum
    (0.540, 0.790, 0.790, 1.0),  # teal
    (0.975, 0.705, 0.575, 1.0),  # apricot
]


REPO_ROOT = Path(__file__).resolve().parents[1]

# (relative-path, view-suffix) for each example.
# Each directory must contain ``view_input.glb`` and ``view_assembly_{suffix}.glb``
# whose i-th geometry corresponds to the i-th geometry of its sibling (matching
# vertex counts), so palette[i] gives the same color to the same part in both
# files. The suffix matches the numeric tag used in the filenames generated by
# the inference pipeline (e.g. ``9`` for partnext/bone, ``-1`` for breakingbad).
EXAMPLES = [
    ("static/models/partnext/1",                "9"),
    ("static/models/partnext/2",                "9"),
    ("static/models/partnext/3",                "9"),
    ("static/models/bone/talus",                "9"),
    ("static/models/breakingbad/fractured_50",  "-1"),
    # Generation-with-image-condition qualitative grid.
    ("static/generation_img/beerbottle",                            "9"),
    ("static/generation_img/bown",                                  "9"),
    ("static/generation_img/spoon",                                 "9"),
    ("static/generation_img/0a3d54c6c030444aaa334ba6db9110f6",      "9"),
    ("static/generation_img/0a9d96e62a5245a59f00a546c1e69a12",      "9"),
    ("static/generation_img/0ac6af36ac6a4502a58275a5079048ff",      "9"),
    ("static/generation_img/0af130ac34bd4ea284606f1820ca2578",      "9"),
    ("static/generation_img/0e1fa6d6afde445f981e0f4c6473b7e2",      "9"),
    ("static/generation_img/0e294f50ff6c4db5b87b1693cf316d6b",      "9"),
    ("static/generation_img/0f95c13e132344dea539440a918acfd5",      "9"),
    # Generation-without-image-condition qualitative grid (no .png inputs).
    ("static/generation_woimg/vase",                                "-1"),
    ("static/generation_woimg/winebottle",                          "-1"),
    ("static/generation_woimg/1aa71039c31d41c5bddbe9bce0adef45",    "-1"),
    ("static/generation_woimg/1b095ffc7c264993b9d7530a339cf6cf",    "-1"),
    ("static/generation_woimg/1b47d22b3bb44cfc9aef9ffedd93ffdd",    "-1"),
    ("static/generation_woimg/1e5cddb968df3efa94437adfc3930a08",    "-1"),
]


def make_material(index: int, name_prefix: str) -> PBRMaterial:
    r, g, b, a = MACARON[index % len(MACARON)]
    return PBRMaterial(
        name=f"{name_prefix}_part_{index}",
        baseColorFactor=[r, g, b, a],
        metallicFactor=0.0,
        roughnessFactor=0.85,
        doubleSided=True,
    )


def recolor_scene(src: Path, dst: Path, explode: bool = False) -> None:
    scene = trimesh.load(src, force=None)
    if not isinstance(scene, trimesh.Scene):
        # Single-mesh GLBs (shouldn't happen for partnext, but be defensive).
        scene = trimesh.Scene(geometry=scene)

    # Sort geometry keys deterministically by their trailing integer
    # (geometry_0, geometry_1, ...). Falls back to lexicographic if a key
    # doesn't follow that pattern.
    def key_idx(k: str) -> tuple[int, str]:
        tail = k.rsplit("_", 1)[-1]
        try:
            return (0, f"{int(tail):010d}")
        except ValueError:
            return (1, k)

    ordered_keys = sorted(scene.geometry.keys(), key=key_idx)
    # Disambiguate material names across examples (e.g. "1", "talus") so that
    # browsers/loaders don't dedupe materials with identical names across files.
    name_prefix = f"{src.parent.parent.name}_{src.parent.name}"

    # Pivot for the exploded view = mean of per-part vertex centers (each
    # part weighted equally, regardless of vertex count). Computed once up
    # front so every part shares the same reference point.
    pivot = None
    if explode and EXPLODE_FACTOR != 0.0:
        centers = []
        for key in ordered_keys:
            verts = np.asarray(scene.geometry[key].vertices, dtype=np.float64)
            if len(verts) > 0:
                centers.append(verts.mean(axis=0))
        if centers:
            pivot = np.mean(np.stack(centers, axis=0), axis=0)

    for i, key in enumerate(ordered_keys):
        geom = scene.geometry[key]
        material = make_material(i, name_prefix)

        if pivot is not None:
            verts = np.asarray(geom.vertices, dtype=np.float64)
            if len(verts) > 0:
                center = verts.mean(axis=0)
                displacement = EXPLODE_FACTOR * (center - pivot)
                geom.vertices = verts + displacement

        # Drop any existing per-vertex / per-face color visuals so the material's
        # baseColorFactor isn't multiplied by stray vertex colors on export.
        if hasattr(geom, "visual"):
            try:
                geom.visual = TextureVisuals(material=material)
            except Exception:
                # Fallback: stamp the material directly if the geometry can't
                # accept a fresh TextureVisuals (e.g. point cloud).
                geom.visual.material = material  # type: ignore[attr-defined]
        else:
            geom.visual = TextureVisuals(material=material)

    scene.export(dst)
    explode_tag = "  [exploded]" if pivot is not None else ""
    print(f"  wrote {dst.relative_to(REPO_ROOT)}  ({len(ordered_keys)} parts){explode_tag}")


def targets_for(suffix: str) -> list[tuple[str, str, bool]]:
    # (src_name, dst_name, explode) — only the condition view gets exploded;
    # the assembly view must keep its predicted poses intact.
    return [
        ("view_input.glb",                   "view_input_colored.glb",                True),
        (f"view_assembly_{suffix}.glb",      f"view_assembly_{suffix}_colored.glb",   False),
    ]


def main() -> None:
    for rel_path, suffix in EXAMPLES:
        example_dir = REPO_ROOT / rel_path
        if not example_dir.exists():
            print(f"skip (missing dir): {rel_path}")
            continue
        print(f"{rel_path}:")
        for src_name, dst_name, explode in targets_for(suffix):
            src = example_dir / src_name
            if not src.exists():
                print(f"  skip (missing): {src.relative_to(REPO_ROOT)}")
                continue
            dst = example_dir / dst_name
            recolor_scene(src, dst, explode=explode)


if __name__ == "__main__":
    main()
